server:
  port: 7900  #指定该服务的端口号
eureka:
  instance:
    prefer-ip-address: true # 是否显示主机IP
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/ #指定eureka注册中心地址
spring:
  application:
    name: microservice-eureka-order  ## 指定次应用名称