server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/

spring:
  application:
    name: socialgwx-gateway-zuul
##  路由配置
zuul:
  routes:
    eureka-client:
     serviceId: microservice-eureka-order # zuul的唯一标识
     path: /order/**  #需要映射的路径
    ## service-id: microservice-eureka-order # Eureka 中的serviceId

